#!/usr/bin/env bash
# kb-wallpaper — set keyboard backlight to the wallpaper accent color
# generated by end-4/dots-hyprland via matugen
#
# Usage:  kb-wallpaper [brightness]   (brightness 0-100, default 100)
# Alias:  alias kb-wallpaper='bash ~/.local/bin/kb-wallpaper.sh'

set -euo pipefail

BRIGHTNESS="${1:-100}"
_KB="${_KB:-/sys/devices/platform/faustus/leds}"   # adjust if needed

# ── locate matugen color cache ─────────────────────────────────────────────────
# end-4 dotfiles write matugen output to one of these locations:
CANDIDATES=(
    "$HOME/.cache/matugen/colors.json"
    "$HOME/.config/matugen/colors.json"
    "$HOME/.cache/ags/user/generated/colors/colors.json"
)

COLOR_FILE=""
for f in "${CANDIDATES[@]}"; do
    [[ -f "$f" ]] && { COLOR_FILE="$f"; break; }
done

# fallback: find any matugen colors.json under .cache
if [[ -z "$COLOR_FILE" ]]; then
    COLOR_FILE=$(find "$HOME/.cache" -maxdepth 4 -name "colors.json" 2>/dev/null | head -1)
fi

# ── extract hex color ──────────────────────────────────────────────────────────
extract_hex() {
    # Try matugen v0.10+ format  → .colors.primary.dark.hex
    local hex
    hex=$(python3 -c "
import json, sys
data = json.load(open('$1'))
c = data.get('colors', data)
# Walk common key paths
for path in [
    ['colors','primary','dark','hex'],
    ['colors','primary','light','hex'],
    ['colors','tertiary','dark','hex'],
    ['primary','dark','hex'],
    ['primary','hex'],
]:
    node = c
    try:
        for k in path:
            node = node[k]
        # strip leading #
        print(str(node).lstrip('#'))
        sys.exit(0)
    except (KeyError, TypeError):
        pass
# last-resort: grab first hex-looking value recursively
import re
text = json.dumps(data)
m = re.search(r'[0-9a-fA-F]{6}', text)
if m: print(m.group())
" 2>/dev/null) || true
    echo "$hex"
}

if [[ -n "$COLOR_FILE" ]]; then
    HEX=$(extract_hex "$COLOR_FILE")
fi

# ── fallback: read from generated scss/gtk variables ──────────────────────────
if [[ -z "${HEX:-}" ]]; then
    for scss in \
        "$HOME/.cache/ags/user/generated/colors/colors-dark.scss" \
        "$HOME/.cache/ags/user/generated/colors/colors.scss" \
        "$HOME/.config/gtk-4.0/gtk.css"
    do
        [[ -f "$scss" ]] || continue
        HEX=$(grep -oP '(?<=\$primary[^:]*:\s#)[0-9a-fA-F]{6}' "$scss" | head -1) && break
        HEX=$(grep -oP '(?<=--md-sys-color-primary:\s#)[0-9a-fA-F]{6}' "$scss" | head -1) && break
    done
fi

# ── final fallback: use end-4 pywal/colors file ───────────────────────────────
if [[ -z "${HEX:-}" ]]; then
    PYWAL="$HOME/.cache/wal/colors.json"
    [[ -f "$PYWAL" ]] && HEX=$(python3 -c "
import json
d = json.load(open('$PYWAL'))
print(d['colors']['color2'].lstrip('#'))
" 2>/dev/null) || true
fi

if [[ -z "${HEX:-}" ]]; then
    echo "kb-wallpaper: could not find a generated color — is matugen/end-4 set up?" >&2
    exit 1
fi

# ── hex → R G B ───────────────────────────────────────────────────────────────
HEX="${HEX^^}"   # uppercase for clarity
R=$(( 16#${HEX:0:2} ))
G=$(( 16#${HEX:2:2} ))
B=$(( 16#${HEX:4:2} ))

# ── write to keyboard (4 zones, same color) ───────────────────────────────────
ZONE="${R},${G},${B}"
PAYLOAD="${ZONE},${ZONE},${ZONE},${ZONE},${BRIGHTNESS}"

echo "kb-wallpaper: #${HEX}  →  ${PAYLOAD}"
echo "$PAYLOAD" | sudo tee "${_KB}/per_zone_mode" > /dev/null
